server:
  port: 8072
  servlet:
    session:
      timeout: 0

kim:
  web:
    enable-cross-domain: true

code:
  data:
#    base-path: ${user.home}/ars/dbhelp
#    theme-dic-name: themeList
    git-enable: true
    git-url: https://gitee.com/resources1/themeList.git
#    git-user:
#    git-pwd:
#    branch: