server:
  port: 8072
  servlet:
    session:
      timeout: 0

spring:
  profiles:
    active: dev
  application:
    name: dbhelp-service-api

kim:
  web:
    enable-cross-domain: true

knife4j:
  enable: false
  openapi:
    title: 数据库帮助工具和代码生成
    version: v1.0
    group:
      dbhelp:
        group-name: dbhelp-service-api
        api-rule: package
        api-rule-resources:
          - com.dbhelp.controller
code:
  data:
#    base-path: ${user.home}/ars/dbhelp
#    theme-dic-name: themeList
    git-enable: true
    git-url: https://gitee.com/resources1/themeList.git
#    git-user:
#    git-pwd:
#    branch:

---
spring:
  config:
    activate:
      on-profile: dev
knife4j:
  enable: true

---
spring:
  config:
    activate:
      on-profile: test

knife4j:
  enable: false